prepare package for cnpm
rogii-com/googletest pull request #2
Opened 2019-07-09 11:23 UTC by chak3r

2019-07-09 12:04 UTC, gshep requested changes

2019-07-09 12:04 UTC, gshep commented on cmake/build_amd64.cmake
> +)
maybe it's better to use env var

2019-07-09 12:04 UTC, gshep commented on package.cmake
> +
empty line

2019-07-09 12:04 UTC, gshep commented on package.cmake
> +                INTERFACE_LINK_LIBRARIES Threads::Threads)
make conformant to the rest

2019-07-09 12:04 UTC, gshep commented on googletest/CMakeLists.txt
> +    ""
unite to one call

2019-07-09 12:51 UTC, chak3r commented on cmake/build_amd64.cmake
> +)
fixed

2019-07-09 12:51 UTC, chak3r commented on package.cmake
> +
fixed?

2019-07-09 12:51 UTC, chak3r commented on package.cmake
> +                INTERFACE_LINK_LIBRARIES Threads::Threads)
fixed

2019-07-09 12:51 UTC, chak3r commented on googletest/CMakeLists.txt
> +    ""
done

2019-07-10 04:29 UTC, gshep requested changes

2019-07-10 04:29 UTC, gshep commented on cmake/build_common.cmake
> +    "gtest-${VERSION}-${ARCH}-${BUILD}$ENV{TAG}"
just TAG, non ENV{TAG}

2019-07-10 06:16 UTC, chak3r commented on cmake/build_common.cmake
> +    "gtest-${VERSION}-${ARCH}-${BUILD}$ENV{TAG}"
fixed

2019-07-10 06:33 UTC, gshep approved these changes

2019-07-10 06:55 UTC, merged